export interface OptionItem {
  ko: string;
  en: string;
}

export interface CompanyData {
  departments: OptionItem[];
  positions: OptionItem[];
  qualifications?: OptionItem[];
}

export const CHEIL_COMPANY_DATA: CompanyData = {
  departments: [
    { ko: "임원실", en: "Executive Management" },
    { ko: "교통인프라사업본부", en: "Transportation Infrastructure Division" },
    { ko: "도로사업부", en: "Highway Engineering" },
    { ko: "교통팀", en: "Mobility Planning & ITS" },
    { ko: "공항팀", en: "Airport Engineering" },
    { ko: "스마트 -X 사업부", en: "Smart-X Div." },
    { ko: "스마트시티사업팀", en: "Smart City Team" },
    { ko: "AX/DX 사업팀", en: "AX/DX Team" },
    { ko: "에코솔루션사업부", en: "Eco Solution Business" },
    { ko: "산업플랜트사업팀", en: "Industrial Plant" },
    { ko: "신재생에너지사업팀", en: "New & Renewable Energy" },
    { ko: "온실가스감축사업팀", en: "Sustainable Engineering" },
    { ko: "물인프라사업본부", en: "Water Infrastructure Division" },
    { ko: "상하수도사업1부", en: "Water & Wastewater 1" },
    { ko: "상하수도사업2부", en: "Water & Wastewater 2" },
    { ko: "운영관리팀", en: "Operations & Management Team" },
    { ko: "수자원사업부", en: "Water Resources" },
    { ko: "환경플랜트팀", en: "Environmental Engineering" },
    { ko: "철도사업본부", en: "Rail & Transit Division" },
    { ko: "철도사업부", en: "Railway Engineering" },
    { ko: "철도감리사업부", en: "Rail Construction Management" },
    { ko: "해외철도사업팀", en: "International Railway" },
    { ko: "국토도시본부", en: "Urban & Regional Planning Division" },
    { ko: "단지사업부", en: "Land & Site Development" },
    { ko: "생태조경사업부", en: "Ecological Landscape" },
    { ko: "도시사업부", en: "Urban Planning & Development" },
    { ko: "구조기반사업본부", en: "Structural & Geotechnical Division" },
    { ko: "구조사업부", en: "Structural Engineering" },
    { ko: "지반사업부", en: "Tunnels & Geotechnical Engineering" },
    { ko: "안전진단사업부", en: "Infrastructure Safety Inspection" },
    { ko: "CM사업부문", en: "CM Division" },
    { ko: "토목CM사업본부", en: "Infrastructure CM Division" },
    { ko: "토목CM1부", en: "Infrastructure CM 1" },
    { ko: "토목CM2부", en: "Infrastructure CM 2" },
    { ko: "건축CM사업본부", en: "Architecture CM Division" },
    { ko: "건축CM1부", en: "Architecture CM 1" },
    { ko: "건축CM2부", en: "Architecture CM 2" },
    { ko: "건축설계사업본부", en: "Architecture Division" },
    { ko: "건축설계1부", en: "Architecture Design 1" },
    { ko: "건축설계2부", en: "Architecture Design 2" },
    { ko: "환경사업부", en: "Environment Business" },
    { ko: "해외본부", en: "International Business" },
    { ko: "영업전략실", en: "Business Development" },
    { ko: "경영지원본부", en: "Corporate Services Division" },
    { ko: "재무회계부", en: "Finance & Accounting" },
    { ko: "인사총무부", en: "Human Resources & Administration" },
    { ko: "사업지원부", en: "Proposal Management" },
    { ko: "업무부", en: "Project & Contract Administration" },
    { ko: "기획실", en: "Strategic Planning" },
    { ko: "전산실", en: "IT Services" },
    { ko: "SIS연구소", en: "Smart Infrastructure Systems Research Institute" },
    { ko: "SHE 경영실", en: "EHS Management" },
    { ko: "항만팀(항만사업부)", en: "Harbor & Coastal" },
  ],
  positions: [
    { ko: "부장", en: "General Manager" },
    { ko: "부사장", en: "Executive Vice President" },
    { ko: "감리단장", en: "Chief Engineer" },
    { ko: "상무", en: "Managing Director" },
    { ko: "사원", en: "Assistant Section Head." },
    { ko: "이사", en: "Director" },
    { ko: "부회장", en: "Executive Vice Chairman" },
    { ko: "주임", en: "Assistant Manager" },
    { ko: "차장", en: "Deputy General Manager" },
    { ko: "전무", en: "Executive Director" },
  ],
  qualifications: [
    { ko: "상하수도기술사", en: "Chief Engineer" },
    { ko: "토목구조기술사", en: "Civil Business Div." },
    { ko: "기술사", en: "Professional Engineer" },
    { ko: "토목시공기술사", en: "Professional Engineer Civil Engineering" },
    { ko: "공학박사", en: "Ph.D" },
    { ko: "토질 및 기초기술사", en: "P.E." },
    { ko: "폐기물처리기술사", en: "P.E." },
    { ko: "교통공학박사/교통기술사", en: "Ph.D. P.E." },
    { ko: "교통기술사", en: "P.E." },
    { ko: "공항 및 공항기술사", en: "P.E." },
    { ko: "책임기술사/기술사", en: "P.E." },
    { ko: "철도기술사", en: "Engineer Railway" },
    { ko: "도로 및 공항 기술사", en: "Professional Engineer / Highway & Airport" },
  ],
};

export const HANMI_COMPANY_DATA: CompanyData = {
  departments: [
    { ko: "국내사업부", en: "Domestic Division" },
    { ko: "하이테크사업부", en: "High-Tech Division" },
    { ko: "글로벌사업부", en: "Global Division" },
    { ko: "엔지니어링실", en: "Engineering Division" },
    { ko: "경영지원", en: "Management Support" },
  ],
  positions: [
    { ko: "사장", en: "President" },
    { ko: "부사장", en: "Senior Vice President" },
    { ko: "전무", en: "Vice President" },
    { ko: "이사", en: "Director" },
    { ko: "시니어 매니저", en: "Senior Manager" },
    { ko: "매니저", en: "Manager" },
    { ko: "프로", en: "Professional" },
    { ko: "국내사업부장", en: "Head of Domestic Division" },
    { ko: "하이테크사업부장", en: "Head of High-Tech Division" },
    { ko: "개발사업부장", en: "Head of Development Division" },
    { ko: "글로벌사업부장", en: "Head of Global Division" },
    { ko: "기술총괄", en: "Head of Engineering Division" },
    { ko: "엔지니어링실장", en: "Division Leader" },
    { ko: "실장", en: "Team Leader" },
    { ko: "팀장", en: "Team Leader" },
    { ko: "단장", en: "Project Manager" },
  ],
};
